// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuYWbj_9XMI7Zy-jo4FfENRM1UMhS1HFg',
    appId: '1:716266086691:web:c786c2bb61f173068bac96',
    messagingSenderId: '716266086691',
    projectId: 'carebot-525da',
    authDomain: 'carebot-525da.firebaseapp.com',
    storageBucket: 'carebot-525da.firebasestorage.app',
    measurementId: 'G-7Z8724NDWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz83XDQ82XNIxp66eGVNaFbGTTyZBYrdg',
    appId: '1:716266086691:android:808bc3ee7a8f90f38bac96',
    messagingSenderId: '716266086691',
    projectId: 'carebot-525da',
    storageBucket: 'carebot-525da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSFjEwAfZ0urrySWmAifkc5djwslWWaws',
    appId: '1:716266086691:ios:362b2ee1aacc70be8bac96',
    messagingSenderId: '716266086691',
    projectId: 'carebot-525da',
    storageBucket: 'carebot-525da.firebasestorage.app',
    iosBundleId: 'com.example.carebot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSFjEwAfZ0urrySWmAifkc5djwslWWaws',
    appId: '1:716266086691:ios:362b2ee1aacc70be8bac96',
    messagingSenderId: '716266086691',
    projectId: 'carebot-525da',
    storageBucket: 'carebot-525da.firebasestorage.app',
    iosBundleId: 'com.example.carebot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuYWbj_9XMI7Zy-jo4FfENRM1UMhS1HFg',
    appId: '1:716266086691:web:689e48383a261ba88bac96',
    messagingSenderId: '716266086691',
    projectId: 'carebot-525da',
    authDomain: 'carebot-525da.firebaseapp.com',
    storageBucket: 'carebot-525da.firebasestorage.app',
    measurementId: 'G-CLJG1RC3JT',
  );
}
